//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf
        ///{\fonttbl {\f0 Futura Md;}{\f1 Futura Hv;}{\f2 Book Antiqua;}{\f3 Cambria;}}
        ///{\colortbl {\red0\green0\blue0;\red66\green105\blue236;\red150\green150\blue150;}}
        ///\f0\fs48 \cf1 \qr \b1 Dictionary\b0\par
        ///\fs40 \cf0 Dictionnaire\par
        ///\fs36 Woordenboek\par
        ///Faclair\par
        ///\u1493\&apos;3f\u1493\&apos;3f\u1506\&apos;3f\u1512\&apos;3f\u1496\&apos;3f\u1506\&apos;3f\u1512\&apos;3f\u1489\&apos;3f\u1493\&apos;3f\u1498\&apos;3f\par
        ///\u2437\&apos;3f\u2477\&apos;3f\u2495\&apos;3f\u2471\&apos;3f\u2494\&apos;3f\u2472\&apos;3f\par
        ///\u0955\&apos;3f\u0949\&apos;3f\u0958\&apos;3f\u0953\&apos;3f\u0954\&apos;3f\u0972\&apos;3f\par
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rtfHeader {
            get {
                return ResourceManager.GetString("rtfHeader", resourceCulture);
            }
        }
    }
}
